name: Git to Composer Storage
description: Sync DAGS and Plugins buckets with git repo folders
inputs:
  secrets:
    description: base64 of corresponding access key files
    required: true
  bucket:
    description: gcs bucket
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: database
  color: purple
